name: CI-SFTP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-via-sftp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build
        run: |
          npm ci
          npm run build

      - name: SFTP Deploy dist/
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          server:   ${{ secrets.SFTP_SERVER }}   # z.B. www530.your-server.de
          port:     22
          username: ${{ secrets.SFTP_USERNAME }} # z.B. jfahom
          password: ${{ secrets.SFTP_PASSWORD }}
          #ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          sftp_only: true
          local_path: 'dist'                     # Ordner, NICHT 'dist/*'
          remote_path: 'public_html/'             # relativ, kein führender '/'
          sftpArgs: '-o ConnectTimeout=5'

